#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf && rm -rf $HOME/.config/tmux
ln -s $DOTFILES/tmux $HOME/.config/tmux

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/hypr
ln -s $DOTFILES/hypr $HOME/.config/hypr

rm -rf $HOME/.config/ags
ln -s $DOTFILES/ags $HOME/.config/ags

rm -rf $HOME/.config/rofi
ln -s $DOTFILES/rofi $HOME/.config/rofi

rm -r $HOME/.zshrc
ln -s $DOTFILES/.zshrc $HOME/.zshrc
